name: idialogue
description: "iDialogue: The solution for language barrier."
publish_to: 'none'
version: 1.3.0


environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  crypto: ^3.0.6
  record: ^6.0.0
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1
  speech_to_text: 7.1.0
  web_socket_channel: ^3.0.3
  loading_indicator: ^3.1.1
  flutter_tts: ^4.2.3
  flutter_contacts: ^1.1.9+2
  lpinyin: ^2.0.2
  icons_launcher: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - defaults/default_dialogue_package.json

icons_launcher:
  image_path: "icon.jpg"
  platforms:
    android:
      enable: true
      image_path: "icon_rounded.jpg"
      notification_image: "icon_foreground.jpg"
      adaptive_foreground_image: "icon_foreground.jpg"
      adaptive_round_image: "icon_rounded.jpg"
      adaptive_background_color: "#ffffff"
    ios:
      enable: true